import React, { useState, useRef, useCallback } from "react";
import type { ReactNode } from "react";
import { createPortal } from "react-dom";
import { Check, X } from "lucide-react";
import { GenerationDetailsPanel } from "../GenerationDetailsPanel";
import type { CardState, EditVariant, CardMeta } from "./types";
import { CardActionBar } from "./CardActionBar";
import { CardStateOverlay } from "./CardStateOverlay";
import { usePopupPosition } from "./usePopupPosition";

const POPUP_WIDTH = 254;
const POPUP_MAX_HEIGHT = 300;
const VIEWPORT_PADDING = 12;

interface CardWrapperProps {
  label: string;
  children: ReactNode;
  state?: CardState;
  onToggleActive?: () => void;
  onRegenerate?: () => void;
  onDelete?: () => void;
  meta?: CardMeta;
  editVariant?: EditVariant;
  onEditEnter?: () => void;
  onEditSave?: () => void;
  onEditCancel?: () => void;
  isEditing?: boolean;
  className?: string;
}

export function CardWrapper({
  label,
  children,
  state = "inactive",
  onToggleActive,
  onRegenerate,
  onDelete,
  meta,
  editVariant,
  onEditEnter,
  onEditSave,
  onEditCancel,
  isEditing,
  className = "",
}: CardWrapperProps) {
  const [showMeta, setShowMeta] = useState(false);
  const infoBtnRef = useRef<HTMLButtonElement>(null);

  const isActive = state === "active";
  const hasOverlay = state === "waiting" || state === "merging" || state === "available";

  const handleCloseMeta = useCallback(() => setShowMeta(false), []);

  const { pos: popupPos, containerRef: metaRef } = usePopupPosition(
    infoBtnRef,
    showMeta,
    handleCloseMeta,
    { width: POPUP_WIDTH, maxHeight: POPUP_MAX_HEIGHT, padding: VIEWPORT_PADDING },
  );

  const borderClass =
    state === "available"
      ? "border-transparent"
      : isActive || isEditing
        ? "border-blue-400 ring-2 ring-blue-300/40 shadow-md shadow-blue-100/60"
        : "border-border/60 hover:border-border/90";

  return (
    <div
      className={`bg-white rounded-xl border overflow-hidden flex flex-col absolute inset-0 transition-all duration-150 group/card
        ${borderClass}
        ${className}`}
    >
      <div className="flex-1 p-5 relative flex flex-col [&_*]:not-italic overflow-y-auto min-h-0">
        {onToggleActive && !hasOverlay && (
          <button
            data-card-toggle
            onClick={(e) => { e.stopPropagation(); onToggleActive(); }}
            className={`absolute top-2.5 right-2.5 w-5 h-5 rounded-full flex items-center justify-center z-10 transition-all duration-150 cursor-pointer group/toggle
              ${isActive
                ? "bg-blue-500 shadow-sm hover:bg-red-400"
                : "bg-white border border-border/50 shadow-sm opacity-30 hover:opacity-100 hover:border-blue-300 hover:bg-blue-50"
              }`}
            title={isActive ? "Deactivate card" : "Set as active"}
          >
            {isActive
              ? <>
                  <Check size={11} className="text-white group-hover/toggle:hidden" strokeWidth={3} />
                  <X size={11} className="text-white hidden group-hover/toggle:block" strokeWidth={3} />
                </>
              : <Check size={11} className="text-muted-foreground/40 group-hover/toggle:text-blue-400" strokeWidth={3} />
            }
          </button>
        )}
        {children}
      </div>

      {!hasOverlay && (
        <CardActionBar
          infoBtnRef={infoBtnRef}
          showMeta={showMeta}
          onToggleMeta={() => setShowMeta((v) => !v)}
          editVariant={editVariant}
          isEditing={isEditing}
          onEditEnter={onEditEnter}
          onEditSave={onEditSave}
          onEditCancel={onEditCancel}
          onRegenerate={onRegenerate}
          onDelete={onDelete}
        />
      )}

      <CardStateOverlay state={state} />

      {showMeta && popupPos && createPortal(
        <div
          ref={metaRef}
          className="fixed z-[9999] bg-white rounded-xl border border-border/60 shadow-xl overflow-hidden"
          style={{
            top: popupPos.top,
            left: popupPos.left,
            width: popupPos.width,
            transform: "translateY(-100%)",
            backdropFilter: "blur(12px)",
            maxHeight: POPUP_MAX_HEIGHT,
          }}
          onClick={(e) => e.stopPropagation()}
        >
          <GenerationDetailsPanel
            meta={meta}
            onClose={handleCloseMeta}
            emptyMessage="Generated by Brand Brew AI"
            maxBodyHeight={230}
          />
        </div>,
        document.body
      )}
    </div>
  );
}
