import React, { type ReactNode } from "react";
import { Cpu, Clock, List, Sparkles, Upload, X } from "lucide-react";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Display-only meta type that unifies CardMeta and SnapshotGenerationMeta
 * so a single panel can render generation info from both card and snapshot contexts.
 */
export interface GenerationDetailsMeta {
  prompt?: string;
  model?: string;
  generationTime?: number;
  ingredients?: string[];
  paletteImageDataUrl?: string;
  /** All URLs are guaranteed to be non-empty strings. */
  referenceImageUrls?: string[];
  /** Human-readable labels for all selected elements (including non-visual ones). */
  selectedElementLabels?: string[];
  /** Set when this variation was created by the user editing another variation. */
  editedFromLabel?: string;
  /** Distinguishes user-uploaded variations from AI-generated ones. */
  source?: "user-upload";
}

export interface GenerationDetailsPanelProps {
  meta?: GenerationDetailsMeta | null;
  onClose?: () => void;
  /** Shown when meta is null/undefined (e.g. "Generated by Brand Brew AI"). */
  emptyMessage?: ReactNode;
  /** Max height for scrollable body (e.g. 230 for popover). */
  maxBodyHeight?: number;
}

// ---------------------------------------------------------------------------
// Internal sub-components
// ---------------------------------------------------------------------------

interface DetailRowProps {
  icon: React.ElementType;
  label: string;
  children: ReactNode;
}

function DetailRow({ icon: Icon, label, children }: DetailRowProps) {
  return (
    <div className="flex items-start gap-2">
      <Icon size={11} className="text-muted-foreground/50 mt-0.5 shrink-0" />
      <div className="min-w-0 flex-1">
        <p className="text-[9px] uppercase tracking-widest text-muted-foreground/50 mb-0.5">
          {label}
        </p>
        {children}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

export function GenerationDetailsPanel({
  meta,
  onClose,
  emptyMessage,
  maxBodyHeight = 300,
}: GenerationDetailsPanelProps) {
  // Derive whether the Inputs section should be shown — and whether it has
  // actual content to display — from the same set of conditions.
  const inputItems = {
    hasPalette: !!meta?.paletteImageDataUrl,
    hasReferenceImages:
      !!meta?.referenceImageUrls && meta.referenceImageUrls.length > 0,
    hasSelectedLabels:
      !!meta?.selectedElementLabels && meta.selectedElementLabels.length > 0,
  };
  const hasAnyInput = Object.values(inputItems).some(Boolean);
  const showInputsSection = hasAnyInput;

  return (
    <>
      {/* Header */}
      <div className="flex items-center justify-between px-3 py-2 border-b border-border/30 bg-muted/20">
        <span className="text-[11px] font-semibold text-muted-foreground uppercase tracking-wider flex items-center gap-1.5">
          <Sparkles size={11} className="text-violet-500" />
          Generation details
        </span>
        {onClose && (
          <button
            type="button"
            onClick={(e) => {
              e.stopPropagation();
              onClose();
            }}
            className="p-0.5 text-muted-foreground/50 hover:text-foreground transition-colors rounded"
            aria-label="Close"
          >
            <X size={11} />
          </button>
        )}
      </div>

      {/* Body */}
      <div
        className="px-3 py-2.5 space-y-2.5 overflow-y-auto"
        // CSS variable avoids creating a new inline-style object on every render.
        style={{ ["--panel-max-h" as string]: `${maxBodyHeight}px`, maxHeight: "var(--panel-max-h)" } as React.CSSProperties}
      >
        {/* Model */}
        {meta?.model && (
          <DetailRow icon={Cpu} label="Model">
            <p className="text-[11px] text-foreground/80 font-mono">{meta.model}</p>
          </DetailRow>
        )}

        {/* Generation time */}
        {meta?.generationTime != null && (
          <DetailRow icon={Clock} label="Generation time">
            <p className="text-[11px] text-foreground/80">
              {meta.generationTime >= 1000
                ? `${(meta.generationTime / 1000).toFixed(1)}s`
                : `${meta.generationTime}ms`}
            </p>
          </DetailRow>
        )}

        {/* Inputs */}
        {showInputsSection && (
          <DetailRow icon={Sparkles} label="Inputs">
            <div className="flex flex-col gap-1">
              {inputItems.hasPalette && (
                <div className="flex items-center gap-1.5">
                  <div className="h-10 max-w-[160px] rounded-md overflow-hidden border border-border/60 bg-muted/40">
                    <img
                      src={meta!.paletteImageDataUrl}
                      alt="Palette"
                      className="h-full w-auto object-contain"
                      draggable={false}
                    />
                  </div>
                  <span className="text-[11px] text-muted-foreground">
                    Color palette input
                  </span>
                </div>
              )}

              {inputItems.hasReferenceImages && (
                <div className="flex flex-wrap gap-1.5">
                  {meta!.referenceImageUrls!.map((url) => (
                    <button
                      key={url}
                      type="button"
                      onClick={(e) => {
                        e.stopPropagation();
                        window.open(url, "_blank", "noopener,noreferrer");
                      }}
                      className="w-10 h-10 rounded-md overflow-hidden border border-border/60 bg-muted/40 hover:border-blue-400 hover:shadow-sm transition-all"
                      title="Open input image"
                    >
                      <img
                        src={url}
                        alt="Input"
                        className="w-full h-full object-cover"
                        draggable={false}
                      />
                    </button>
                  ))}
                </div>
              )}

              {inputItems.hasSelectedLabels && (
                <div className="flex flex-wrap gap-1 mt-0.5">
                  {meta!.selectedElementLabels!.map((label) => (
                    <span
                      key={label}
                      className="text-[10px] px-1.5 py-0.5 rounded-full bg-muted/60 text-muted-foreground"
                    >
                      {label}
                    </span>
                  ))}
                </div>
              )}
            </div>
          </DetailRow>
        )}

        {/* Prompt */}
        {meta?.prompt && (
          <DetailRow icon={Sparkles} label="Prompt">
            <p className="text-[11px] text-foreground/70 leading-relaxed break-words whitespace-pre-wrap">
              {meta.prompt}
            </p>
          </DetailRow>
        )}

        {/* Ingredients */}
        {meta?.ingredients && meta.ingredients.length > 0 && (
          <DetailRow icon={List} label="Ingredients">
            <div className="flex flex-wrap gap-1">
              {meta.ingredients.map((ing) => (
                <span
                  key={ing}
                  className="text-[10px] px-1.5 py-0.5 bg-violet-50 text-violet-600 rounded-full"
                >
                  {ing}
                </span>
              ))}
            </div>
          </DetailRow>
        )}

        {/* User-edited source — shown when the variation was created by editing */}
        {meta?.editedFromLabel && (
          <DetailRow icon={Sparkles} label="Source">
            <p className="text-[11px] text-foreground/70">
              Edited by user from{" "}
              <span className="font-medium text-foreground/80">
                {meta.editedFromLabel}
              </span>
            </p>
          </DetailRow>
        )}

        {/* User-uploaded source */}
        {meta?.source === "user-upload" && (
          <DetailRow icon={Upload} label="Source">
            <p className="text-[11px] text-foreground/70">Uploaded by user</p>
          </DetailRow>
        )}

        {/* Empty state — only shown when meta is absent */}
        {!meta && emptyMessage != null && (
          <DetailRow icon={Sparkles} label="Source">
            <div className="text-[11px] text-foreground/70">{emptyMessage}</div>
          </DetailRow>
        )}
      </div>
    </>
  );
}