import React, { type ReactNode, useRef, useState, useLayoutEffect } from "react";
import { Cpu, FileText, Sparkles, Upload, X, MessageSquare, Tag, Layers, Pencil, GitFork, BookOpen, Info } from "lucide-react";
import { CANVAS, LAYOUT, TYPE } from "../utils/design-tokens";
import { openImageInNewTab } from "../utils/open-image-viewer";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Display-only meta type that unifies VariationMeta and SnapshotGenerationMeta
 * so a single panel can render generation info from both card and snapshot contexts.
 */
export interface GenerationDetailsMeta {
  prompt?: string;
  model?: string;
  agent?: string;
  userInput?: string;
  generationTime?: number;
  ingredients?: string[];
  paletteImageDataUrl?: string;
  /** All URLs are guaranteed to be non-empty strings. */
  referenceImageUrls?: string[];
  /** Human-readable labels for all selected elements (including non-visual ones). */
  selectedElementLabels?: string[];
  /** Set when this variation was created by the user editing another variation. */
  editedFromLabel?: string;
  /** Distinguishes user-uploaded variations from AI-generated ones. */
  source?: "user-upload";
  /** Add variation 来源类型 */
  addVariationSource?: "from-variation" | "original-brand";
  /** 当 addVariationSource 为 from-variation 时，来源 variation 的 id */
  sourceVariationId?: string;
}

export interface GenerationDetailsPanelProps {
  meta?: GenerationDetailsMeta | null;
  onClose?: () => void;
  /** Shown when meta is null/undefined (e.g. "Generated by Brand Brew AI"). */
  emptyMessage?: ReactNode;
  /** Max height for scrollable body (optional cap; viewport limit applied automatically). */
  maxBodyHeight?: number;
  /** Min gap in px between panel bottom and window bottom (default 16). */
  bottomPadding?: number;
}

// ---------------------------------------------------------------------------
// Internal sub-components
// ---------------------------------------------------------------------------

interface DetailRowProps {
  icon: React.ElementType;
  label: string;
  children: ReactNode;
}

function DetailRow({ icon: Icon, label, children }: DetailRowProps) {
  return (
    <div className="flex items-start gap-2">
      <Icon size={TYPE.icon.sm} className="text-muted-foreground/50 mt-0.5 shrink-0" />
      <div className="min-w-0 flex-1">
        <p className="text-[9px] uppercase tracking-widest text-muted-foreground/50 mb-0.5">
          {label}
        </p>
        {children}
      </div>
    </div>
  );
}

function EmptyValue() {
  return <span className="text-[11px] text-muted-foreground/25 select-none">—</span>;
}

// ---------------------------------------------------------------------------
// Model & agent name mapping
// ---------------------------------------------------------------------------

const IMAGE_MODEL_NAMES: Record<string, string> = {
  "gemini-3.1-flash-image-preview": "Nano Banana 2",
  "gemini-3-pro-image-preview": "Nano Banana Pro",
  "gemini-2.5-flash-image": "Nano Banana",
};

const AGENT_DISPLAY_NAMES: Record<string, string> = {
  "brand-strategist": "Brand Strategist",
  "art-director": "Art Director",
  "visual-designer": "Visual Designer",
  "visual-designer-visual-snapshot": "Visual Designer",
  "visual-designer-context": "Visual Designer",
};


function getModelDisplayName(modelName: string): string {
  return IMAGE_MODEL_NAMES[modelName] ?? modelName;
}

// ---------------------------------------------------------------------------
// Main component
// ---------------------------------------------------------------------------

const VIEWPORT_BOTTOM_GAP = LAYOUT.filmstrip.gap;

function useViewportMaxBodyHeight(
  bodyRef: React.RefObject<HTMLDivElement | null>,
  bottomPadding: number,
  propMax?: number,
) {
  const [effectiveMax, setEffectiveMax] = useState<number>(propMax ?? 300);

  useLayoutEffect(() => {
    const el = bodyRef.current;
    if (!el) return;

    const compute = () => {
      const rect = el.getBoundingClientRect();
      const viewportLimit = Math.max(CANVAS.BOTTOM_MARGIN, window.innerHeight - rect.top - bottomPadding);
      const capped = propMax != null ? Math.min(viewportLimit, propMax) : viewportLimit;
      setEffectiveMax(capped);
    };

    compute();

    const ro = new ResizeObserver(compute);
    ro.observe(el);

    const onResize = () => {
      requestAnimationFrame(compute);
    };
    window.addEventListener("resize", onResize);

    return () => {
      ro.disconnect();
      window.removeEventListener("resize", onResize);
    };
  }, [bodyRef, bottomPadding, propMax]);

  return effectiveMax;
}

export function GenerationDetailsPanel({
  meta,
  onClose,
  emptyMessage,
  maxBodyHeight,
  bottomPadding = VIEWPORT_BOTTOM_GAP,
}: GenerationDetailsPanelProps) {
  const bodyRef = useRef<HTMLDivElement>(null);
  const effectiveMaxHeight = useViewportMaxBodyHeight(bodyRef, bottomPadding, maxBodyHeight);

  // Derive whether the Inputs section should be shown — and whether it has
  // actual content to display — from the same set of conditions.
  const inputItems = {
    hasPalette: !!meta?.paletteImageDataUrl,
    hasReferenceImages:
      !!meta?.referenceImageUrls && meta.referenceImageUrls.length > 0,
    hasSelectedLabels:
      !!meta?.selectedElementLabels && meta.selectedElementLabels.length > 0,
  };

  return (
    <>
      {/* Header */}
      <div className="flex items-center justify-between px-3 py-2 border-b border-border/30 bg-muted/20 shrink-0">
        <span className="text-[11px] font-semibold text-muted-foreground uppercase tracking-wider flex items-center gap-1.5">
          <Sparkles size={TYPE.icon.sm} className="text-violet-500" />
          Generation details
        </span>
        {onClose && (
          <button
            type="button"
            onClick={(e) => {
              e.stopPropagation();
              onClose();
            }}
            className="p-0.5 text-muted-foreground/50 hover:text-foreground transition-colors rounded"
            aria-label="Close"
          >
            <X size={TYPE.icon.sm} />
          </button>
        )}
      </div>

      {/* Body */}
      <div
        ref={bodyRef}
        className="px-3 py-2.5 space-y-2.5 overflow-y-auto min-h-0 flex-1"
        style={{ maxHeight: effectiveMaxHeight }}
      >
        {/* 1. Source */}
        {(() => {
          if (meta?.editedFromLabel) return (
            <DetailRow icon={Pencil} label="Source">
              <p className="text-[11px] text-foreground/70">
                Edited from{" "}
                <span className="font-medium text-foreground/80">{meta.editedFromLabel}</span>
              </p>
            </DetailRow>
          );
          if (meta?.source === "user-upload") return (
            <DetailRow icon={Upload} label="Source">
              <p className="text-[11px] text-foreground/70">Uploaded by user</p>
            </DetailRow>
          );
          if (meta?.addVariationSource === "original-brand") return (
            <DetailRow icon={BookOpen} label="Source">
              <p className="text-[11px] text-foreground/70">Added from original brand data</p>
            </DetailRow>
          );
          if (meta?.addVariationSource === "from-variation" || meta?.sourceVariationId) return (
            <DetailRow icon={GitFork} label="Source">
              <p className="text-[11px] text-foreground/70">
                Added from variation{" "}
                {meta?.sourceVariationId && (
                  <span className="font-mono text-foreground/80" title={meta.sourceVariationId}>
                    {meta.sourceVariationId.slice(0, 8)}…
                  </span>
                )}
              </p>
            </DetailRow>
          );
          if (meta?.agent) return (
            <DetailRow icon={Sparkles} label="Source">
              <p className="text-[11px] text-foreground/70">
                Generated by{" "}
                <span className="font-medium text-violet-600">
                  {AGENT_DISPLAY_NAMES[meta.agent] ?? meta.agent}
                </span>
              </p>
            </DetailRow>
          );
          return (
            <DetailRow icon={Info} label="Source">
              {emptyMessage != null
                ? <div className="text-[11px] text-foreground/70">{emptyMessage}</div>
                : <EmptyValue />}
            </DetailRow>
          );
        })()}

        {/* 2. Run by — model / time */}
        <DetailRow icon={Cpu} label="Run by">
          {(meta?.model || meta?.generationTime != null) ? (
            <p className="text-[11px] text-foreground/70">
              {[
                meta!.model ? getModelDisplayName(meta!.model) : null,
                meta!.generationTime != null
                  ? (meta!.generationTime >= 1000
                      ? `${(meta!.generationTime / 1000).toFixed(1)}s`
                      : `${meta!.generationTime}ms`)
                  : null,
              ].filter(Boolean).join(" · ")}
            </p>
          ) : <EmptyValue />}
        </DetailRow>

        {/* 3. User input */}
        <DetailRow icon={MessageSquare} label="User input">
          {meta?.userInput
            ? <p className="text-[11px] text-foreground/80 leading-relaxed break-words italic">"{meta.userInput}"</p>
            : <EmptyValue />}
        </DetailRow>

        {/* 4. Brand brief — ingredients */}
        <DetailRow icon={Tag} label="Brand brief">
          {(() => {
            const items = (meta?.ingredients ?? []).filter(
              (ing) => ing && !ing.startsWith("http") && ing.length <= 120
            );
            return items.length > 0 ? (
              <div className="flex flex-wrap gap-1">
                {items.map((ing, i) => (
                  <span
                    key={`${i}-${ing}`}
                    className="text-[10px] px-1.5 py-0.5 bg-muted/60 text-foreground/70 rounded max-w-[180px] truncate"
                    title={ing}
                  >
                    {ing}
                  </span>
                ))}
              </div>
            ) : <EmptyValue />;
          })()}
        </DetailRow>

        {/* 5. Selected elements */}
        <DetailRow icon={Layers} label="Selected elements">
          {(inputItems.hasSelectedLabels || inputItems.hasPalette || inputItems.hasReferenceImages) ? (
            <div className="flex flex-col gap-1.5">
              {inputItems.hasSelectedLabels && (
                <div className="flex flex-wrap gap-1">
                  {meta!.selectedElementLabels!.map((label, i) => (
                    <span
                      key={`${i}-${label}`}
                      className="text-[10px] px-1.5 py-0.5 rounded-full bg-violet-50 text-violet-600"
                    >
                      {label}
                    </span>
                  ))}
                </div>
              )}
              {inputItems.hasPalette && (
                <div className="flex items-center gap-1.5">
                  <div className="h-8 max-w-[140px] rounded overflow-hidden border border-border/60 bg-muted/40">
                    <img
                      src={meta!.paletteImageDataUrl}
                      alt="Palette"
                      className="h-full w-auto object-contain"
                      draggable={false}
                    />
                  </div>
                </div>
              )}
              {inputItems.hasReferenceImages && (
                <div className="flex flex-wrap gap-1.5">
                  {meta!.referenceImageUrls!.map((url, i) => (
                    <button
                      key={`${i}-${url}`}
                      type="button"
                      onClick={(e) => { e.stopPropagation(); openImageInNewTab(url, "Input Image"); }}
                      className="w-8 h-8 rounded overflow-hidden border border-border/60 bg-muted/40 hover:border-blue-400 hover:shadow-sm transition-all"
                      title="Open input image"
                    >
                      <img src={url} alt="Input" className="w-full h-full object-cover" draggable={false} />
                    </button>
                  ))}
                </div>
              )}
            </div>
          ) : <EmptyValue />}
        </DetailRow>

        {/* 6. Prompt */}
        <DetailRow icon={FileText} label="Prompt">
          {meta?.prompt
            ? <p className="text-[11px] text-foreground/60 leading-relaxed break-words whitespace-pre-wrap">{meta.prompt}</p>
            : <EmptyValue />}
        </DetailRow>
      </div>
    </>
  );
}
